site_name: kiara.streamlit
repo_url: https://github.com/DHARPA-project/kiara.streamlit
site_author: Markus Binsteiner
docs_dir: docs
site_dir: build/site

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking

markdown_extensions:
- attr_list
- admonition
- codehilite:
    guess_lang: false
- toc:
    permalink: true
- pymdownx.snippets:
    base_path: docs

nav:
- Home: index.md
- Usage: usage.md

extra:
  version:
    provider: mike

plugins:
- search
- mknotebooks
- mkdocstrings:
    default_handler: python
    watch:
      - "src"
#- frkl-docgen:
#    main_module: "kiara_streamlit"
- macros:
   modules:
     - kiara.doc.mkdocs_macros_cli
     - kiara.doc.mkdocs_macros_kiara

#- gen-files:
#    scripts:
#      - scripts/documentation/gen_module_doc.py
